name: scripts

# CINTENT >> MANUAL_TRIGGER
# on:
#   workflow_run:
#     workflows: ["builds"]
#     types: [completed]
on: [repository_dispatch, workflow_dispatch]

jobs:
  test-analyze:
    # CINTENT >> REMOVE_TRIGGER
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # CINTENT >> UNSUPPORTED_OS
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]

        # CINTENT >> REMOVE_MATRIX
        # python: [3.7, 3.8]
        python: [3.8]
    steps:
      - if: matrix.os == 'macos-latest'
        name: Install MacOS prerequisites
        run: brew install cairo pango gdk-pixbuf libffi

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      
      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@a606c80c34ec190c6a20dea33d6d58ddb6c4e0cc

      # CINTENT >> REMOVE_CACHE          
      # - name: Cache python modules
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('**/*.py') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}-
      #       ${{ runner.os }}-pkg-deps-${{ matrix.python }}-
      #       ${{ runner.os }}-pkg-deps-
      #       ${{ runner.os }}-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tf] --upgrade

      - name: Run analysis script
        run: |
          wget https://github.com/mindee/doctr/releases/download/v0.1.0/sample.pdf
          python scripts/analyze.py sample.pdf --noblock

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}